/* Generated by AI Phind*/

/** @type {import('tailwindcss').Config} */
module.exports = {
    content: [
        "./Pages/**/*.{cshtml,razor,cs,js}",
        "./Views/**/*.{cshtml,razor,cs,js}",
        "./Components/**/*.{cshtml,razor,cs,js}",
        "./Pages/**/*.cshtml.css",
        "./Views/**/*.cshtml.css",
        "./Components/**/*.razor.css"
    ],
    theme: {
        extend: {},
    },
    plugins: [],
}