/* Generated by AI Phind*/

/** @type {import('tailwindcss').Config} */
module.exports = {
    content: [
        "./Views/**/*.cshtml",
        "./Pages/**/*.cshtml",
        "./Areas/**/*.cshtml"
    ],
    theme: {
        extend: {},
    },
    plugins: [],
}